version: "3"
services:
  notebook:
    build: .
    ports:
      # docker-compose v1に限り、scaleオプションで複数コンテナを起動するとコンテナごとに異なるホスト側ポートが割り当てられる
      - "8080-8082:8888"
    volumes:
      - python-packages:/root/.local/share
volumes:
  python-packages: